---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: toystore
    environment: dev
  name: toystore-svc
  #namespace: dev
spec:
  type: NodePort
  selector:
    app: toystore
  ports:
  - name: http
    port: 8080
    targetPort: 8080