pipeline {      
         agent {
                   label "slave"
                   }
           parameters {
             string(name: 'NAMESPACE', defaultValue: '', description: 'the target namespace'), string(name: 'dbImageID', defaultValue: '', description: 'Database docker image ID'), string(name: 'appImageID', defaultValue: '', description: 'Toy0Store app docker image ID')
           }
           
    stages {
  /*      stage('Checkout project') {
        steps {
            
            git branch: 'master',
                credentialsId: 'Github',
                url: 'https://github.com/ahmedmisbah-ole/Devops-Orange'
        }
    } */
     
/*      stage('Deploy') {
         steps {
             script{
                     
                     sh """ 
                     echo "${params.NAMESPACE}" 
                     cd ${WORKSPACE}/manifests
                     kubectl apply -f database/ --namespace "${params.NAMESPACE}"
                     kubectl apply -f app/ -n "${params.NAMESPACE}"
                     """
                     
                }
            }  
        } */
           stage ('Deploy') {
           steps {
               script{
                   sh """
                   echo ${params.appImageID}
                   echo ${params.dbImageID}
                   sed -i s/dbImageID/${params.dbImageID}/ ${WORKSPACE}/manifests/database/deployment.yaml
                   sed -i s/appImageID/${params.appImageID}/ ${WORKSPACE}/manifests/app/deployment.yaml
                   cd ${WORKSPACE}/playbooks/
                   ansible-playbook  database-deployment.yaml --extra-vars \"ImageID=${params.ImageID} "NAMESPACE=${params.NAMESPACE}\""
                   sleep 20
                   ansible-playbook  toystore-deployment.yaml --extra-vars \"ImageID=${params.ImageID} "NAMESPACE=${params.NAMESPACE}\""
                   """
               }
           }
       } 
    
    }
}
