pipeline {      
         agent {
                   label "slave"
                   }
           parameters {
           string(name: 'NAMESPACE', defaultValue: '', description: 'the target namespace')
           }
    stages {
  /*      stage('Checkout project') {
        steps {
            
            git branch: 'master',
                credentialsId: 'Github',
                url: 'https://github.com/ahmedmisbah-ole/Devops-Orange'
        }
    } */
     
/*      stage('Deploy') {
         steps {
             script{
                     
                     sh """ 
                     echo "${params.NAMESPACE}" 
                     cd ${WORKSPACE}/manifests
                     kubectl apply -f database/ --namespace "${params.NAMESPACE}"
                     kubectl apply -f app/ -n "${params.NAMESPACE}"
                     """
                     
                }
            }  
        } */
           stage ('Deploy') {
           steps {
               script{
                   def image_id = registry + ":$BUILD_NUMBER"
                   sh "cd playbooks/ && ansible-playbook  toystore-deployment.yml --extra-vars \"NAMESPACE=${parmsNAMESPACE}\""
               }
           }
       } 
    
    }
}
