- hosts: localhost
  tasks:
  - name: Deploy toystore configmap
    k8s:
      state: present
      definition: "{{ lookup('template', '../manifests/app/config-map.yaml') | from_yaml }}"
      validate_certs: no
      namespace:  "{{ NAMESPACE }}"
  - name: Deploy toystore service-account
    k8s:
      state: present
      definition: "{{ lookup('template', '../manifests/app/svc-account.yaml') | from_yaml }}"
      validate_certs: no
      namespace:  "{{ NAMESPACE }}"
  - name: Deploy toystore service
    k8s:
      state: present
      definition: "{{ lookup('template', '../manifests/app/service.yaml') | from_yaml }}"
      validate_certs: no
      namespace:  "{{ NAMESPACE }}"